name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.1.0
        with:
          version: master

      - run: zig version
      - run: zig env
      - run: zig build
      - run: zig build test
      - run: ./zig-out/bin/zbf
      - run: ./zig-out/bin/zbf examples/sierpinski.b
